#!/bin/sh
set -e

SRC=$(pwd)
cd "$AUTOPKGTEST_TMP"

g++ -Wall "$SRC/examples/pmemkv_basic_cpp/pmemkv_basic.cpp" -lpmemkv

./a.out foo | tee log

diff -u - log <<END
Creating config
Opening pmemkv database with 'cmap' engine
Putting new key
Reading key back
Iterating existing keys
  visited: key3
  visited: key2
  visited: key1
Defragmenting the database
Removing existing key
Closing database
END
