#!/bin/sh
set -e

SRC=$(pwd)
cd "$AUTOPKGTEST_TMP"

gcc -Wall "$SRC/examples/pmemkv_basic_c/pmemkv_basic.c" -lpmemkv

./a.out foo | tee log

diff -u - log <<END
Creating config
Opening pmemkv database with 'cmap' engine
Putting new key
Reading key back
Iterating existing keys
   visited: key3
   visited: key2
   visited: key1
Removing existing key
Defragmenting the database
Closing database
END
